version: '3'

services:
  api:
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./api/target/rym-1.0.jar:/app/rym-1.0.jar

  postgres:
    restart: unless-stopped
    image: postgres:16.1-alpine3.18
    ports:
      - ${PG_PORT}:5432
    environment:
      - POSTGRES_DB=rym
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./api/data/pgadmin:/var/lib/pgadmin
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
